FROM python3
ENV PYTHONUNBUFFERED=1
COPY requirements.txt ./
RUN pip3.10 install -r requirements.txt

COPY . .

CMD ["python3", "manage.py", "makemigrations"]
CMD ["python3", "manage.py", "migrate"]
CMD ["python3", "manage.py", "runserver", "0:80"]