# Generated by Django 4.0.6 on 2022-07-26 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='bio',
            new_name='description',
        ),
    ]
