# Generated by Django 4.0.6 on 2022-07-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='buyer_ID',
        ),
        migrations.AlterField(
            model_name='user',
            name='orders_number',
            field=models.IntegerField(default=0, verbose_name='Количество заказов'),
        ),
        migrations.AlterField(
            model_name='user',
            name='orders_sum',
            field=models.IntegerField(default=0, verbose_name='Сумма заказов'),
        ),
    ]
